import { type NextRequest, NextResponse } from "next/server"

// SVG 기반 이미지 생성 (서버리스 환경에서 안전)
export async function GET(request: NextRequest, { params }: { params: { username: string } }) {
  try {
    const { username } = params

    // GitHub 데이터 가져오기
    const githubResponse = await fetch(`${request.nextUrl.origin}/api/cat/${username}`)
    const githubData = await githubResponse.json()

    // SVG 이미지 생성
    const svg = generateCatSVG(githubData)

    return new NextResponse(svg, {
      headers: {
        "Content-Type": "image/svg+xml",
        "Cache-Control": "public, max-age=3600",
      },
    })
  } catch (error) {
    console.error("Image generation error:", error)

    // 에러 SVG 반환
    const errorSvg = generateErrorSVG()
    return new NextResponse(errorSvg, {
      headers: {
        "Content-Type": "image/svg+xml",
        "Cache-Control": "public, max-age=300",
      },
    })
  }
}

function generateCatSVG(data: any): string {
  const { username, commitCount, catStage } = data

  const catColors = ["#A0A0A0", "#FFB366", "#FF9A56", "#D2691E", "#8B7D6B", "#696969", "#FFD700"]
  const catNames = [
    "Sleepy Cat",
    "Baby Kitten",
    "Curious Kitten",
    "Active Cat",
    "Adult Cat",
    "Developer Cat",
    "Master Cat",
  ]

  const color = catColors[catStage] || "#FFB366"
  const name = catNames[catStage] || "Unknown Cat"

  return `
    <svg width="400" height="200" xmlns="http://www.w3.org/2000/svg">
      <!-- Background -->
      <rect width="400" height="200" fill="#f8fafc"/>
      <rect x="20" y="20" width="360" height="160" fill="white" stroke="#e5e7eb" stroke-width="2" rx="10"/>
      
      <!-- Cat Body -->
      <circle cx="120" cy="100" r="40" fill="${color}"/>
      
      <!-- Cat Ears -->
      <circle cx="100" cy="70" r="15" fill="${color}"/>
      <circle cx="140" cy="70" r="15" fill="${color}"/>
      <circle cx="100" cy="70" r="8" fill="#FFB6C1"/>
      <circle cx="140" cy="70" r="8" fill="#FFB6C1"/>
      
      <!-- Cat Eyes -->
      <circle cx="110" cy="90" r="5" fill="black"/>
      <circle cx="130" cy="90" r="5" fill="black"/>
      <circle cx="112" cy="88" r="2" fill="white"/>
      <circle cx="132" cy="88" r="2" fill="white"/>
      
      <!-- Cat Nose -->
      <circle cx="120" cy="100" r="3" fill="#ff69b4"/>
      
      <!-- Cat Mouth -->
      <path d="M 115 105 Q 120 110 125 105" stroke="#ff69b4" stroke-width="2" fill="none"/>
      
      <!-- Cat Tail -->
      <ellipse cx="80" cy="120" rx="20" ry="8" fill="${color}" transform="rotate(-30 80 120)"/>
      
      <!-- Text Info -->
      <text x="200" y="60" font-family="Arial, sans-serif" font-size="24" font-weight="bold" fill="#1f2937">@${username}</text>
      <text x="200" y="90" font-family="Arial, sans-serif" font-size="18" fill="#374151">${name}</text>
      <text x="200" y="115" font-family="Arial, sans-serif" font-size="16" fill="#6b7280">${commitCount} commits this year</text>
      <text x="200" y="140" font-family="Arial, sans-serif" font-size="16" fill="#6b7280">Level ${catStage}</text>
      
      <!-- GitPaws Branding -->
      <text x="200" y="170" font-family="Arial, sans-serif" font-size="12" fill="#9ca3af" text-anchor="middle">Generated by GitPaws 🐾</text>
      
      <!-- Sparkles for higher levels -->
      ${
        catStage >= 5
          ? `
        <text x="160" y="50" font-size="16">✨</text>
        <text x="340" y="60" font-size="16">⭐</text>
        <text x="350" y="140" font-size="16">💫</text>
      `
          : ""
      }
      
      <!-- Crown for master cat -->
      ${
        catStage === 6
          ? `
        <polygon points="110,50 120,40 130,50 125,55 115,55" fill="#FFD700" stroke="#FFA500" stroke-width="1"/>
        <circle cx="120" cy="45" r="3" fill="#FF0000"/>
      `
          : ""
      }
    </svg>
  `
}

function generateErrorSVG(): string {
  return `
    <svg width="400" height="200" xmlns="http://www.w3.org/2000/svg">
      <rect width="400" height="200" fill="#fee2e2"/>
      <text x="200" y="100" font-family="Arial, sans-serif" font-size="20" fill="#dc2626" text-anchor="middle">😿 Cat not found</text>
      <text x="200" y="130" font-family="Arial, sans-serif" font-size="14" fill="#dc2626" text-anchor="middle">Please try again later</text>
    </svg>
  `
}
